### ISSUE TITLE
建议页面上更新课程信息

### ISSUE THREAD

**Issue by cuihaoleo** [zhyx12/sfsj2018#2]
第一节说明课程信息的 PPT 没有在网站上发布，有些同学第一节课可能没来或者没有记录下，希望更新到 README.md 中以便查询。

主要是作业信息等，包括：
- 书面作业提交时间限制
- 编程作业的提交邮箱和时间限制
- 其他重要的课程信息

**Comment by zhyx12** [comment]
感谢师弟提醒，已经更新了部分信息，课件会马上更新
