### ISSUE TITLE
提交作业时邮件发送失败

### ISSUE THREAD

**Issue by zht022** [zhyx12/sfsj2018#3]
我提交作业的时候用科大邮箱或者qq邮箱发送都失败了，科大邮箱给出的退信原因是：

由于对方服务器不稳定，或者双方服务器网络连接质量不佳，或者防火墙过滤，而无法连接上对方服务器。
Can not connect to recipient's server because of unstable network or firewall filter.

我连续试了几天都无法发送，请问一下助教或者各位同学有什么解决办法？

**Comment by zhyx12** [comment]
要不你先发到我的邮箱 zhyx12@mail.ustc.edu.cn 或者 zhyx12@gmail.com
